# Generated by Django 3.1.2 on 2020-10-07 22:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_domain', models.TextField(blank=True, null=True)),
                ('cloud_path', models.TextField(blank=True, null=True)),
                ('cloud_port', models.TextField(blank=True, null=True)),
                ('cloud_protocol', models.TextField(blank=True, null=True)),
                ('cloud_register_procedure', models.TextField(blank=True, null=True)),
                ('copyright', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('docs', models.TextField(blank=True, null=True)),
                ('encoding', models.TextField(blank=True, null=True)),
                ('generator', models.TextField(blank=True, null=True)),
                ('image_description', models.TextField(blank=True, null=True)),
                ('image_height', models.TextField(blank=True, null=True)),
                ('image_link', models.TextField(blank=True, null=True)),
                ('image_title', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('image_width', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('managing_editor', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('text_input_description', models.TextField(blank=True, null=True)),
                ('text_input_link', models.TextField(blank=True, null=True)),
                ('text_input_name', models.TextField(blank=True, null=True)),
                ('text_input_title', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('ttl', models.TextField(blank=True, null=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('web_master', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField()),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('enclosure_length', models.TextField(blank=True, null=True)),
                ('enclosure_type', models.TextField(blank=True, null=True)),
                ('enclosure_url', models.TextField(blank=True, null=True)),
                ('guid', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField()),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='feedsubscription',
            name='feeds_feed_owner_url_key',
        ),
        migrations.AddConstraint(
            model_name='feedsubscription',
            constraint=models.UniqueConstraint(fields=('owner', 'url'), name='feeds_feedsubscription_owner_url_key'),
        ),
        migrations.AddField(
            model_name='feeditemcategory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='feeds.feeditem'),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feeds.feed'),
        ),
        migrations.AddField(
            model_name='feedcategory',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='feeds.feed'),
        ),
        migrations.AddField(
            model_name='feed',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='feeds.feedsubscription'),
        ),
        migrations.AddConstraint(
            model_name='feeditem',
            constraint=models.UniqueConstraint(fields=('feed', 'link'), name='feeds_feeditem_feed_link_key'),
        ),
    ]
