# Generated by Django 3.1.2 on 2020-10-08 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_create_feed_data_structures'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeditem',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedsubscription',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedsubscription',
            name='retries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedsubscription',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('failure', 'Failure'), ('success', 'Success')], default='new', max_length=11),
        ),
        migrations.AlterField(
            model_name='feed',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
