# Generated by Django 3.1.2 on 2020-10-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_add_fields_to_feed_and_feed_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedsubscription',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('ready', 'Ready')], default='new', max_length=11),
        ),
    ]
